### ISSUE TITLE
How to represent associated resources in CKAN

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/ckan#108]
if two datasets are linked in some way, either because one is an aggregation of another or they are just related studies, one dataset can be linked to by another in xml using the '<mri:associatedResource>' tag. We can harvest this into ckan easily enough.

Should associated resources stored as regular resources in CKAN?

Should we represent these resources differently than other resources? Perhaps with a special badge or section on the dataset pages?

How are these types of resources represented by other ckan instances? Would. be good to know if/how others do this.

**Comment by sjbruce** [comment]
To clarify our terms:
 - Is an associated resource in this context always an independent dataset with its own, complete metadata record?
 - Or are we, potentially, including CKAN resources, as in links to external pages, services, etc?  If so, is there any scenario where a CKAN resource is only ever _associated_ with a proper dataset but otherwise orphaned?  i.e. it has no primary dataset of its own.
 - Can you point to an example of this scenario within CIOOS currently?  It'd be handy to wrap ones head around it.

**Comment by sjbruce** [comment]
It might be worth talking to Rich Signell @ USGS - he's gave a presentation about exploring the CKAN API at DMAC last year: https://ioos.noaa.gov/project/dmac/ 

USGS also has a number of datasets **and collections** on https://catalog.data.gov/organization/usgs-gov

Could be some useful examples in there.

**Comment by sjbruce** [comment]
While these scenarios occur, they are fairly rare and require the data providers to provide these linkages as CIOOS will not proactively try to establish them.

Related datasets need require to be published before they can be linked - this may require revisiting and republishing a dataset in order to establish those links due to the random generation of dataset IDs.

**Example:** https://hecate.hakai.org/geonetwork/srv/eng/catalog.search#/metadata/26443ab2-964f-4031-a53b-f132434573e8

**Preliminary Approach:**
 - Add a section for related datasets to appear below the resource list for a dataset
 - Add a "Show More" area for both the existing resources list and the associated datasets that kicks in if there more than a configured value (5 for a start?)

**Comment by fostermh** [comment]
working example: https://catalogue.hakai.org/dataset/cf7a6149-b34a-404c-88e1-c556bf361408

![Screen Shot 2021-07-05 at 3 34 26 PM](https://user-images.githubusercontent.com/6304992/124522022-845e1500-dda6-11eb-9238-96af8685f4b4.png)

**Comment by fostermh** [comment]
code for this has been implemented in our ckan catalogues. Waiting on metadata form to implement input portion.

**Comment by Br-Johnson** [comment]
The [DataCite metadata schema](https://schema.datacite.org/meta/kernel-4.4/) provides a mechanism for this as well using 'Related Identifiers' field. If the CKAN DOI extension was used to optionally register DOIs, it seems this method of specifying dataset relations is the most fleshed out and universal.
